# Generated by Django 4.1 on 2022-09-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('specialzation', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=20)),
                ('fees', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='static/')),
            ],
        ),
    ]
