# Generated by Django 4.1 on 2022-09-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='date',
        ),
    ]
