# Generated by Django 4.1 on 2022-09-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_history_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='disc',
            field=models.TextField(blank=True),
        ),
    ]
