# Generated by Django 4.1 on 2022-09-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_history_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'Histories'},
        ),
    ]
